package net.wolfur.rasputin.bungie.type;

public enum DestinyDefinitionType {

    DESTINY_ENEMY_RACE_DEFINITION("DestinyEnemyRaceDefinition"),
    DESTINY_NODE_STEP_SUMMARY_DEFINITION("DestinyNodeStepSummaryDefinition"),
    DESTINY_ART_DYE_CHANNEL_DEFINITION("DestinyArtDyeChannelDefinition"),
    DESTINY_ART_DYE_REFERENCE_DEFINITION("DestinyArtDyeReferenceDefinition"),
    DESTINY_PLACE_DEFINITION("DestinyPlaceDefinition"),
    DESTINY_ACTIVITY_DEFINITION("DestinyActivityDefinition"),
    DESTINY_ACTIVITY_TYPE_DEFINITION("DestinyActivityTypeDefinition"),
    DESTINY_CLASS_DEFINITION("DestinyClassDefinition"),
    DESTINY_GENDER_DEFINITION("DestinyGenderDefinition"),
    DESTINY_INVENTORY_BUCKET_DEFINITION("DestinyInventoryBucketDefinition"),
    DESTINY_RACE_DEFINITION("DestinyRaceDefinition"),
    DESTINY_TALENT_GRID_DEFINITION("DestinyTalentGridDefinition"),
    DESTINY_UNLOCK_DEFINITION("DestinyUnlockDefinition"),
    DESTINY_MATERIAL_REQUIREMENT_SET_DEFINITION("DestinyMaterialRequirementSetDefinition"),
    DESTINY_SANDBOX_PERK_DEFINITION("DestinySandboxPerkDefinition"),
    DESTINY_STAT_GROUP_DEFINITION("DestinyStatGroupDefinition"),
    DESTINY_PROGRESSION_MAPPING_DEFINITION("DestinyProgressionMappingDefinition"),
    DESTINY_FACTION_DEFINITION("DestinyFactionDefinition"),
    DESTINY_VENDOR_GROUP_DEFINITION("DestinyVendorGroupDefinition"),
    DESTINY_REWARD_SOURCE_DEFINITION("DestinyRewardSourceDefinition"),
    DESTINY_UNLOCK_VALUE_DEFINITION("DestinyUnlockValueDefinition"),
    DESTINY_REWARD_MAPPING_DEFINITION("DestinyRewardMappingDefinition"),
    DESTINY_REWARD_SHEET_DEFINITION("DestinyRewardSheetDefinition"),
    DESTINY_ITEM_CATEGORY_DEFINITION("DestinyItemCategoryDefinition"),
    DESTINY_DAMAGE_TYPE_DEFINITION("DestinyDamageTypeDefinition"),
    DESTINY_ACTIVITY_MODE_DEFINITION("DestinyActivityModeDefinition"),
    DESTINY_MEDAL_TIER_DEFINITION("DestinyMedalTierDefinition"),
    DESTINY_ACHIEVEMENT_DEFINITION("DestinyAchievementDefinition"),
    DESTINY_ACTIVITY_GRAPH_DEFINITION("DestinyActivityGraphDefinition"),
    DESTINY_ACTIVITY_INTERACTABLE_DEFINITION("DestinyActivityInteractableDefinition"),
    DESTINY_BOND_DEFINITION("DestinyBondDefinition"),
    DESTINY_CHARACTER_CUSTOMIZATION_CATEGORY_DEFINITION("DestinyCharacterCustomizationCategoryDefinition"),
    DESTINY_CHARACTER_CUSTOMIZATION_OPTION_DEFINITION("DestinyCharacterCustomizationOptionDefinition"),
    DESTINY_COLLECTIBLE_DEFINITION("DestinyCollectibleDefinition"),
    DESTINY_DESTINATION_DEFINITION("DestinyDestinationDefinition"),
    DESTINY_ENTITLEMENT_OFFER_DEFINITION("DestinyEntitlementOfferDefinition"),
    DESTINY_EQUIPMENT_SLOT_DEFINITION("DestinyEquipmentSlotDefinition"),
    DESTINY_STAT_DEFINITION("DestinyStatDefinition"),
    DESTINY_INVENTORY_ITEM_DEFINITION("DestinyInventoryItemDefinition"),
    DESTINY_INVENTORY_ITEM_LITE_DEFINITION("DestinyInventoryItemLiteDefinition"),
    DESTINY_ITEM_TIER_TYPE_DEFINITION("DestinyItemTierTypeDefinition"),
    DESTINY_LOCATION_DEFINITION("DestinyLocationDefinition"),
    DESTINY_LORE_DEFINITION("DestinyLoreDefinition"),
    DESTINY_METRIC_DEFINITION("DestinyMetricDefinition"),
    DESTINY_OBJECTIVE_DEFINITION("DestinyObjectiveDefinition"),
    DESTINY_PLATFORM_BUCKET_MAPPING_DEFINITION("DestinyPlatformBucketMappingDefinition"),
    DESTINY_PLUG_SET_DEFINITION("DestinyPlugSetDefinition"),
    DESTINY_POWER_CAP_DEFINITION("DestinyPowerCapDefinition"),
    DESTINY_PRESENTATION_NODE_DEFINITION("DestinyPresentationNodeDefinition"),
    DESTINY_PRESENTATION_NODE_BASE_DEFINITION("DestinyPresentationNodeBaseDefinition"),
    DESTINY_PROGRESSION_DEFINITION("DestinyProgressionDefinition"),
    DESTINY_PROGRESSION_LEVEL_REQUIREMENT_DEFINITION("DestinyProgressionLevelRequirementDefinition"),
    DESTINY_RECORD_DEFINITION("DestinyRecordDefinition"),
    DESTINY_REWARD_ADJUSTER_POINTER_DEFINITION("DestinyRewardAdjusterPointerDefinition"),
    DESTINY_REWARD_ADJUSTER_PROGRESSION_MAP_DEFINITION("DestinyRewardAdjusterProgressionMapDefinition"),
    DESTINY_REWARD_ITEM_LIST_DEFINITION("DestinyRewardItemListDefinition"),
    DESTINY_SACK_REWARD_ITEM_LIST_DEFINITION("DestinySackRewardItemListDefinition"),
    DESTINY_SANDBOX_PATTERN_DEFINITION("DestinySandboxPatternDefinition"),
    DESTINY_SEASON_DEFINITION("DestinySeasonDefinition"),
    DESTINY_SEASON_PASS_DEFINITION("DestinySeasonPassDefinition"),
    DESTINY_SOCKET_CATEGORY_DEFINITION("DestinySocketCategoryDefinition"),
    DESTINY_SOCKET_TYPE_DEFINITION("DestinySocketTypeDefinition"),
    DESTINY_TRAIT_DEFINITION("DestinyTraitDefinition"),
    DESTINY_TRAIT_CATEGORY_DEFINITION("DestinyTraitCategoryDefinition"),
    DESTINY_UNLOCK_COUNT_MAPPING_DEFINITION("DestinyUnlockCountMappingDefinition"),
    DESTINY_UNLOCK_EVENT_DEFINITION("DestinyUnlockEventDefinition"),
    DESTINY_UNLOCK_EXPRESSION_MAPPING_DEFINITION("DestinyUnlockExpressionMappingDefinition"),
    DESTINY_VENDOR_DEFINITION("DestinyVendorDefinition"),
    DESTINY_MILESTONE_DEFINITION("DestinyMilestoneDefinition"),
    DESTINY_ACTIVITY_MODIFIER_DEFINITION("DestinyActivityModifierDefinition"),
    DESTINY_REPORT_REASON_CATEGORY_DEFINITION("DestinyReportReasonCategoryDefinition"),
    DESTINY_ARTIFACT_DEFINITION("DestinyArtifactDefinition"),
    DESTINY_BREAKER_TYPE_DEFINITION("DestinyBreakerTypeDefinition"),
    DESTINY_CHECKLIST_DEFINITION("DestinyChecklistDefinition"),
    DESTINY_ENERGY_TYPE_DEFINITION("DestinyEnergyTypeDefinition");

    private final String pathName;

    DestinyDefinitionType(String pathName) {
        this.pathName = pathName;
    }

    public String getPathName() {
        return this.pathName;
    }
}
